# Generated by Django 3.0.4 on 2020-03-26 19:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 19, 55, 45, 1865, tzinfo=utc)),
        ),
    ]
